#!/usr/bin/env bash
# =============================================================================
#  BarcodeHID — Linux system setup
#  Configures /dev/uinput permissions for the standard build.
#  Creates a terminal-agnostic desktop launcher.
#  Safe to re-run at any time.
#
#  Usage:
#    bash setup.sh           # interactive
#    bash setup.sh --quiet   # non-interactive (used by build.sh)
# =============================================================================
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUIET=0
for arg in "$@"; do [[ "$arg" == "--quiet" ]] && QUIET=1; done

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
ok()   { echo -e "${GREEN}  ✔  $1${NC}"; }
info() { echo -e "${YELLOW}  →  $1${NC}"; }

[ "$QUIET" = "0" ] && {
  echo ""
  echo "╔══════════════════════════════════════════════════╗"
  echo "║         BarcodeHID — Linux Setup                 ║"
  echo "╚══════════════════════════════════════════════════╝"
  echo ""
}

# ── uinput kernel module ──────────────────────────────────────────────────────
info "Loading uinput kernel module..."
sudo modprobe uinput
grep -q "^uinput" /etc/modules-load.d/uinput.conf 2>/dev/null \
  || echo "uinput" | sudo tee /etc/modules-load.d/uinput.conf > /dev/null
ok "uinput module loaded and configured for boot"

# ── udev rule ─────────────────────────────────────────────────────────────────
RULE='SUBSYSTEM=="misc", KERNEL=="uinput", MODE="0660", GROUP="input"'
FILE="/etc/udev/rules.d/99-barcodehid.rules"
if [ ! -f "$FILE" ] || ! grep -qF "$RULE" "$FILE"; then
  info "Creating udev rule..."
  echo "$RULE" | sudo tee "$FILE" > /dev/null
  sudo udevadm control --reload-rules && sudo udevadm trigger
  ok "udev rule created: $FILE"
else
  ok "udev rule already exists"
fi

# ── input group ───────────────────────────────────────────────────────────────
NEED_RELOGIN=0
if ! groups "$USER" | grep -q '\binput\b'; then
  info "Adding $USER to 'input' group..."
  sudo usermod -aG input "$USER"
  NEED_RELOGIN=1
  ok "Added — log out and back in for this to take effect"
else
  ok "$USER already in 'input' group"
fi

# ── Terminal-agnostic launcher ────────────────────────────────────────────────
LAUNCHER="$DIR/launch.sh"
cat > "$LAUNCHER" << 'EOF'
#!/usr/bin/env bash
# BarcodeHID — terminal-agnostic launcher (generated by setup.sh)
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CMD="$DIR/barcodehid; echo; echo '--- Press Enter to close ---'; read"

# Ordered by preference: modern terminals first, classic fallbacks last.
# Add your terminal here if it's missing.
TERMINALS=(
  "ghostty|-e bash -c"
  "wezterm|start -- bash -c"
  "kitty|bash -c"
  "alacritty|-e bash -c"
  "foot|-e bash -c"
  "gnome-terminal|-- bash -c"
  "konsole|-e bash -c"
  "xfce4-terminal|-e bash -c"
  "mate-terminal|-e bash -c"
  "lxterminal|-e bash -c"
  "tilix|-e bash -c"
  "xterm|-e bash -c"
)

for entry in "${TERMINALS[@]}"; do
  bin="${entry%%|*}"; args="${entry##*|}"
  if command -v "$bin" &>/dev/null; then
    exec "$bin" $args "$CMD"
  fi
done

# Fallback: already in a terminal — run directly
if [ -t 1 ]; then
  cd "$DIR" && ./barcodehid
else
  echo "No terminal emulator found. Run: $DIR/barcodehid" >&2
  exit 1
fi
EOF
chmod +x "$LAUNCHER"
ok "launch.sh created"

# ── .desktop file ─────────────────────────────────────────────────────────────
DESKTOP="$DIR/barcodehid.desktop"
cat > "$DESKTOP" << DTOP
[Desktop Entry]
Version=1.0
Type=Application
Name=BarcodeHID
Comment=Barcode scanner — scan with phone, type on PC
Exec=$LAUNCHER
Icon=input-keyboard
Terminal=false
Categories=Utility;
StartupNotify=false
DTOP
chmod +x "$DESKTOP"

DDIR="$HOME/Desktop"
if [ -d "$DDIR" ]; then
  cp "$DESKTOP" "$DDIR/barcodehid.desktop"
  chmod +x "$DDIR/barcodehid.desktop"
  ok "Launcher copied to Desktop"
fi
ok "Desktop launcher created"

# ── Done ──────────────────────────────────────────────────────────────────────
[ "$QUIET" = "0" ] && {
  echo ""
  echo "╔══════════════════════════════════════════════════╗"
  echo "║  ✅  Setup complete!                             ║"
  echo "╠══════════════════════════════════════════════════╣"
  if [ "$NEED_RELOGIN" = "1" ]; then
  echo "║  ⚠  Log out and back in, then:                  ║"
  fi
  echo "║  → Double-click barcodehid.desktop              ║"
  echo "║  → Or run: ./barcodehid                         ║"
  echo "╚══════════════════════════════════════════════════╝"
  echo ""
}
